#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: 8b93847
#
Name     : R-webmockr
Version  : 2.0.0
Release  : 57
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/webmockr_2.0.0.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/webmockr_2.0.0.tar.gz
Summary  : Stubbing and Setting Expectations on 'HTTP' Requests
Group    : Development/Tools
License  : MIT
Requires: R-R6
Requires: R-cli
Requires: R-crul
Requires: R-curl
Requires: R-fauxpas
Requires: R-jsonlite
Requires: R-magrittr
Requires: R-rlang
Requires: R-urltools
BuildRequires : R-R6
BuildRequires : R-cli
BuildRequires : R-crul
BuildRequires : R-curl
BuildRequires : R-fauxpas
BuildRequires : R-jsonlite
BuildRequires : R-magrittr
BuildRequires : R-rlang
BuildRequires : R-urltools
BuildRequires : buildreq-R

%description
Includes tools for stubbing 'HTTP' requests, including expected
    request conditions and response conditions. Match on
    'HTTP' method, query parameters, request body, headers and
    more. Can be used for unit tests or outside of a testing 
    context.

%prep
%setup -q -n webmockr
pushd ..
cp -a webmockr buildavx2
popd
pushd ..
cp -a webmockr buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1739373600

%install
export SOURCE_DATE_EPOCH=1739373600
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/webmockr/DESCRIPTION
/usr/lib64/R/library/webmockr/INDEX
/usr/lib64/R/library/webmockr/LICENSE
/usr/lib64/R/library/webmockr/Meta/Rd.rds
/usr/lib64/R/library/webmockr/Meta/features.rds
/usr/lib64/R/library/webmockr/Meta/hsearch.rds
/usr/lib64/R/library/webmockr/Meta/links.rds
/usr/lib64/R/library/webmockr/Meta/nsInfo.rds
/usr/lib64/R/library/webmockr/Meta/package.rds
/usr/lib64/R/library/webmockr/NAMESPACE
/usr/lib64/R/library/webmockr/NEWS.md
/usr/lib64/R/library/webmockr/R/webmockr
/usr/lib64/R/library/webmockr/R/webmockr.rdb
/usr/lib64/R/library/webmockr/R/webmockr.rdx
/usr/lib64/R/library/webmockr/help/AnIndex
/usr/lib64/R/library/webmockr/help/aliases.rds
/usr/lib64/R/library/webmockr/help/paths.rds
/usr/lib64/R/library/webmockr/help/webmockr.rdb
/usr/lib64/R/library/webmockr/help/webmockr.rdx
/usr/lib64/R/library/webmockr/html/00Index.html
/usr/lib64/R/library/webmockr/html/R.css
/usr/lib64/R/library/webmockr/ignore/adapter-httr.R
/usr/lib64/R/library/webmockr/ignore/sockets.R
/usr/lib64/R/library/webmockr/tests/test-all.R
/usr/lib64/R/library/webmockr/tests/testthat/crul_body_upload_list.rda
/usr/lib64/R/library/webmockr/tests/testthat/crul_body_upload_no_list.rda
/usr/lib64/R/library/webmockr/tests/testthat/crul_obj.rda
/usr/lib64/R/library/webmockr/tests/testthat/helper-webmockr.R
/usr/lib64/R/library/webmockr/tests/testthat/httr2_obj.rda
/usr/lib64/R/library/webmockr/tests/testthat/httr2_obj_auth.rda
/usr/lib64/R/library/webmockr/tests/testthat/httr_body_upload_list.rda
/usr/lib64/R/library/webmockr/tests/testthat/httr_body_upload_no_list.rda
/usr/lib64/R/library/webmockr/tests/testthat/httr_obj.rda
/usr/lib64/R/library/webmockr/tests/testthat/httr_obj_auth.rda
/usr/lib64/R/library/webmockr/tests/testthat/test-Adapter.R
/usr/lib64/R/library/webmockr/tests/testthat/test-CrulAdapter.R
/usr/lib64/R/library/webmockr/tests/testthat/test-HashCounter.R
/usr/lib64/R/library/webmockr/tests/testthat/test-HttpLibAdapaterRegistry.R
/usr/lib64/R/library/webmockr/tests/testthat/test-Httr2Adapter.R
/usr/lib64/R/library/webmockr/tests/testthat/test-HttrAdapter.R
/usr/lib64/R/library/webmockr/tests/testthat/test-RequestPattern.R
/usr/lib64/R/library/webmockr/tests/testthat/test-RequestRegistry.R
/usr/lib64/R/library/webmockr/tests/testthat/test-RequestSignature.R
/usr/lib64/R/library/webmockr/tests/testthat/test-Response.R
/usr/lib64/R/library/webmockr/tests/testthat/test-StubRegistry.R
/usr/lib64/R/library/webmockr/tests/testthat/test-StubbedRequest.R
/usr/lib64/R/library/webmockr/tests/testthat/test-auth_handling.R
/usr/lib64/R/library/webmockr/tests/testthat/test-b-no-cassette-in-use.R
/usr/lib64/R/library/webmockr/tests/testthat/test-flipswitch.R
/usr/lib64/R/library/webmockr/tests/testthat/test-last_request.R
/usr/lib64/R/library/webmockr/tests/testthat/test-last_stub.R
/usr/lib64/R/library/webmockr/tests/testthat/test-onload.R
/usr/lib64/R/library/webmockr/tests/testthat/test-partial_matching.R
/usr/lib64/R/library/webmockr/tests/testthat/test-pluck_body.R
/usr/lib64/R/library/webmockr/tests/testthat/test-remove_request_stub.R
/usr/lib64/R/library/webmockr/tests/testthat/test-request_registry.R
/usr/lib64/R/library/webmockr/tests/testthat/test-stub_body_diff.R
/usr/lib64/R/library/webmockr/tests/testthat/test-stub_registry.R
/usr/lib64/R/library/webmockr/tests/testthat/test-stub_request.R
/usr/lib64/R/library/webmockr/tests/testthat/test-stub_requests_crul.R
/usr/lib64/R/library/webmockr/tests/testthat/test-to_raise.R
/usr/lib64/R/library/webmockr/tests/testthat/test-to_return.R
/usr/lib64/R/library/webmockr/tests/testthat/test-to_return_body.R
/usr/lib64/R/library/webmockr/tests/testthat/test-to_return_then.R
/usr/lib64/R/library/webmockr/tests/testthat/test-to_timeout.R
/usr/lib64/R/library/webmockr/tests/testthat/test-uri_regex.R
/usr/lib64/R/library/webmockr/tests/testthat/test-webmockr_reset.R
/usr/lib64/R/library/webmockr/tests/testthat/test-wi_th.R
/usr/lib64/R/library/webmockr/tests/testthat/test-within_test_that_blocks.R
/usr/lib64/R/library/webmockr/tests/testthat/test-writing-to-disk-write_disk_path.R
/usr/lib64/R/library/webmockr/tests/testthat/test-writing-to-disk.R
/usr/lib64/R/library/webmockr/tests/testthat/test-zutils.R
